### ISSUE TITLE
1.1 claims to be 1.0.5

### ISSUE THREAD

**Issue by swavkulinski** [linuxgurugamer/KW-Rocketry-Community-Fixes#10]
Hi, downloaded from Spacedock.info and MM complains that this is still 1.0.5

**Comment by linuxgurugamer** [comment]
Ignore it.  It's a version file, if it bothers you, look for a file with a name of .version and edit it, the fields will be self explanatory.

All 1.1 mods are beta, and won't really be finished until 1.1 is fully released.

I'll probably get that updated in a few days, right now I'm busy with upgrading other mods which require significant coding
