### ISSUE TITLE
Textures vs Stock

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/KW-Rocketry-Community-Fixes#11]
First, the tanks do not really match the stock textures, they are very white.  

Second, its kind of nice to have another style, there are enough parts that it doens't matter that they dont mix well with stock parts.  

There are however a few things that are unique and have no comparison in stock.   Such as the Petal Adapters, Interstage Adapters and different style Fairings.  It would be nice if those had a texture switch, to go from their default white to a more stock-alike grey so they could be mixed with stock parts and still look good.

**Comment by linuxgurugamer** [comment]
I'd be happy to add a texture switch, if someone got me the textured

**Comment by eberkain** [comment]
I could probably do the texture edits, not sure which textures tie to which models though.  The KWPetalAdapter3m doesn't have a texture in that folder for example?

**Comment by linuxgurugamer** [comment]
This is the wrong repo.
Closing this, will open one in the correct repo:  https://github.com/linuxgurugamer/KWRocketryRedux

**Comment by linuxgurugamer** [comment]
This is the new issue:
https://github.com/linuxgurugamer/KWRocketryRedux/issues/17
