### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by NathanKell** [linuxgurugamer/KW-Rocketry-Community-Fixes#3]
The PR was accepted, but there's been no new release on KerbalStuff, so anyone trying to use KW and RealismOverhaul (via CKAN) still gets the incompatible version of KW Community Fixes.

**Comment by linuxgurugamer** [comment]
Oops.  I thought I had done that.  I'll take care of it today.

Thanks for the nudge

**Comment by NathanKell** [comment]
Thanks! :)

**Comment by linuxgurugamer** [comment]
Just published the update

JBB
